### ISSUE TITLE
Setting LABEL_MAPPINGS_FILE not respected as demonstrated in README

### ISSUE THREAD

**Issue by fmigneault** [ilyam8/periodic-pr-labeler#6]
`time="2020-05-13T20:29:30Z" level=fatal msg="GET https://api.github.com/repos/crim-ca/weaver/contents/.github/labeler.yml: 404 Not Found []"`

Failing action: 
https://github.com/crim-ca/weaver/pull/139/checks?check_run_id=672235857

https://github.com/crim-ca/weaver/blob/dc9374643d0ad98aefeb8334b4269eabee05cf57/.github/workflows/pr-labeler.yml#L32

Is there a different setting or method to specify the file name? Seems to ignore the env value and still uses the default.

**Comment by ilyam8** [comment]
@fmigneault 👋 

yeah, you are right, just pushed the fix

**Comment by fmigneault** [comment]
Thanks for the quick update :)

**Comment by TGTGamer** [comment]
This hasnt been packaged. So I've just encountered the same issue. Could you package and release this fix.

**Comment by ilyam8** [comment]
It is in the `latest` image, but indeed, i havent released `v*` version, will do

**Comment by ilyam8** [comment]
@TGTGamer done, i released [`v0.1.1`](https://hub.docker.com/layers/ilyam8/periodic-pr-labeler/v0.1.1/images/sha256-acfe1c303c762f911f2d036ebc85bff6346418920260a55fbfdb88a71b096932?context=explore)

**Comment by TGTGamer** [comment]
@ilyam8 Thank you for the fast turnaround. I've included it here: https://github.com/TGTGamer/.github/blob/2128e1b5a205f8c9a3fd9ef39ec780179900e4d0/.github/workflows/cron.yml#L9 and will be using it within the next push to my organisation repos
